-- Retire only the original fixture catalog. Preserve users, credentials, payments and results.

UPDATE capabilities SET enabled=0 WHERE synthetic=1 AND id IN ('datapulse_headcount','companyintel_premium','verifycorp','securescan_advanced','legalarchive','geointel','retail_demand','documentverify','supplychain_radar','patentlens') AND endpoint='demo://' || id;

INSERT INTO providers(id,user_id,name,description,reputation,created_at) SELECT 'provider_gleif_entities',id,'Capora','Search live GLEIF legal-entity records by company name. Returns LEIs, legal names, jurisdictions, registration status and source links. Public data. Price covers retrieval and normalization. Coverage is limited to entities with an LEI, not every business.',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM users WHERE id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO capabilities(id,provider_id,name,description,type,category,price_cents,pricing_unit,input_schema,output_schema,endpoint,expected_latency_ms,baseline_reliability,tags,async,synthetic,documentation_url,availability,created_at) SELECT 'gleif_entities',id,'Company Registry Search','Search live GLEIF legal-entity records by company name. Returns LEIs, legal names, jurisdictions, registration status and source links. Public data. Price covers retrieval and normalization. Coverage is limited to entities with an LEI, not every business.','api','Company intelligence',20,'query','{"type":"object","properties":{"company":{"type":"string","minLength":1,"maxLength":200,"default":"Microsoft"},"limit":{"type":"integer","minimum":1,"maximum":10,"default":5}},"required":["company"],"additionalProperties":false}','{"type":"object","properties":{"synthetic":{"type":"boolean","enum":[false]},"source":{"type":"string"},"sourceUrl":{"type":"string"},"observedAt":{"type":"string"},"license":{"type":"string"},"limitations":{"type":"string"},"data":{"type":"object","properties":{"entities":{"type":"array","items":{"type":"object"}},"total":{"type":"integer","minimum":0}},"required":["entities","total"],"additionalProperties":false}},"required":["synthetic","source","sourceUrl","observedAt","license","limitations","data"],"additionalProperties":false}','builtin://gleif_entities',2000,0,'["company","registry","LEI","public data"]',0,0,'https://www.gleif.org/en/lei-data/gleif-api',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM providers WHERE id='provider_gleif_entities' AND user_id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO providers(id,user_id,name,description,reputation,created_at) SELECT 'provider_crossref_research',id,'Capora','Retrieve live Crossref scholarly metadata with titles, DOI links, authors, publishers and publication dates. Public bibliographic data. Price covers a bounded query and normalization. Does not sell full-text access or patent coverage.',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM users WHERE id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO capabilities(id,provider_id,name,description,type,category,price_cents,pricing_unit,input_schema,output_schema,endpoint,expected_latency_ms,baseline_reliability,tags,async,synthetic,documentation_url,availability,created_at) SELECT 'crossref_research',id,'Research Metadata Search','Retrieve live Crossref scholarly metadata with titles, DOI links, authors, publishers and publication dates. Public bibliographic data. Price covers a bounded query and normalization. Does not sell full-text access or patent coverage.','dataset','Research',25,'query','{"type":"object","properties":{"query":{"type":"string","minLength":1,"maxLength":200,"default":"robotics"},"limit":{"type":"integer","minimum":1,"maximum":10,"default":5}},"required":["query"],"additionalProperties":false}','{"type":"object","properties":{"synthetic":{"type":"boolean","enum":[false]},"source":{"type":"string"},"sourceUrl":{"type":"string"},"observedAt":{"type":"string"},"license":{"type":"string"},"limitations":{"type":"string"},"data":{"type":"object","properties":{"works":{"type":"array","items":{"type":"object"}},"total":{"type":"integer","minimum":0}},"required":["works","total"],"additionalProperties":false}},"required":["synthetic","source","sourceUrl","observedAt","license","limitations","data"],"additionalProperties":false}','builtin://crossref_research',2000,0,'["research","papers","DOI","public data"]',0,0,'https://www.crossref.org/documentation/retrieve-metadata/rest-api/',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM providers WHERE id='provider_crossref_research' AND user_id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO providers(id,user_id,name,description,reputation,created_at) SELECT 'provider_worldbank_indicators',id,'Capora','Retrieve reported World Bank population, GDP or unemployment observations for a country and year range. Public data. Price covers retrieval and normalization. Missing observations remain null and reported years can lag the retrieval date.',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM users WHERE id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO capabilities(id,provider_id,name,description,type,category,price_cents,pricing_unit,input_schema,output_schema,endpoint,expected_latency_ms,baseline_reliability,tags,async,synthetic,documentation_url,availability,created_at) SELECT 'worldbank_indicators',id,'World Bank Economic Indicators','Retrieve reported World Bank population, GDP or unemployment observations for a country and year range. Public data. Price covers retrieval and normalization. Missing observations remain null and reported years can lag the retrieval date.','dataset','Market signals',10,'query','{"type":"object","properties":{"country":{"type":"string","enum":["USA","IND","GBR","DEU","FRA","CAN","AUS","JPN","BRA","CHN"],"default":"USA"},"indicator":{"type":"string","enum":["SP.POP.TOTL","NY.GDP.MKTP.CD","SL.UEM.TOTL.ZS"],"default":"SP.POP.TOTL"},"startYear":{"type":"integer","minimum":1960,"maximum":2100,"default":2020},"endYear":{"type":"integer","minimum":1960,"maximum":2100,"default":2024}},"required":["country","indicator","startYear","endYear"],"additionalProperties":false}','{"type":"object","properties":{"synthetic":{"type":"boolean","enum":[false]},"source":{"type":"string"},"sourceUrl":{"type":"string"},"observedAt":{"type":"string"},"license":{"type":"string"},"limitations":{"type":"string"},"data":{"type":"object","properties":{"observations":{"type":"array","items":{"type":"object"}},"total":{"type":"integer","minimum":0}},"required":["observations","total"],"additionalProperties":false}},"required":["synthetic","source","sourceUrl","observedAt","license","limitations","data"],"additionalProperties":false}','builtin://worldbank_indicators',2000,0,'["economic","GDP","population","public data"]',0,0,'https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structures',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM providers WHERE id='provider_worldbank_indicators' AND user_id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO providers(id,user_id,name,description,reputation,created_at) SELECT 'provider_github_repository',id,'Capora','Retrieve current public GitHub repository metadata: language, license, stars, forks, open issue count and last push. Public data. Price covers retrieval and normalization. Does not clone code, access private repositories or perform a security audit.',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM users WHERE id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO capabilities(id,provider_id,name,description,type,category,price_cents,pricing_unit,input_schema,output_schema,endpoint,expected_latency_ms,baseline_reliability,tags,async,synthetic,documentation_url,availability,created_at) SELECT 'github_repository',id,'GitHub Repository Intelligence','Retrieve current public GitHub repository metadata: language, license, stars, forks, open issue count and last push. Public data. Price covers retrieval and normalization. Does not clone code, access private repositories or perform a security audit.','api','Engineering',15,'query','{"type":"object","properties":{"repository":{"type":"string","minLength":1,"maxLength":200,"default":"cloudflare/workers-sdk"}},"required":["repository"],"additionalProperties":false}','{"type":"object","properties":{"synthetic":{"type":"boolean","enum":[false]},"source":{"type":"string"},"sourceUrl":{"type":"string"},"observedAt":{"type":"string"},"license":{"type":"string"},"limitations":{"type":"string"},"data":{"type":"object","properties":{"repository":{"type":"object"}},"required":["repository"],"additionalProperties":false}},"required":["synthetic","source","sourceUrl","observedAt","license","limitations","data"],"additionalProperties":false}','builtin://github_repository',1500,0,'["repository","GitHub","engineering","public data"]',0,0,'https://docs.github.com/en/rest/repos/repos#get-a-repository',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM providers WHERE id='provider_github_repository' AND user_id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO providers(id,user_id,name,description,reputation,created_at) SELECT 'provider_code_scan',id,'Capora','Run deterministic rules on your supplied code for eval, interpolated SQL and possible embedded credentials. Returns actual line-level findings and remediation. A limited pattern scanner with false positives and false negatives. It does not execute code or audit repositories.',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM users WHERE id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO capabilities(id,provider_id,name,description,type,category,price_cents,pricing_unit,input_schema,output_schema,endpoint,expected_latency_ms,baseline_reliability,tags,async,synthetic,documentation_url,availability,created_at) SELECT 'code_scan',id,'Code Pattern Scan','Run deterministic rules on your supplied code for eval, interpolated SQL and possible embedded credentials. Returns actual line-level findings and remediation. A limited pattern scanner with false positives and false negatives. It does not execute code or audit repositories.','agent','Security',300,'query','{"type":"object","properties":{"code":{"type":"string","minLength":1,"maxLength":100000,"default":"eval(req.body.code)"}},"required":["code"],"additionalProperties":false}','{"type":"object","properties":{"synthetic":{"type":"boolean","enum":[false]},"source":{"type":"string"},"sourceUrl":{"type":"string"},"observedAt":{"type":"string"},"license":{"type":"string"},"limitations":{"type":"string"},"data":{"type":"object","properties":{"linesAnalyzed":{"type":"integer","minimum":1},"findings":{"type":"array","items":{"type":"object"}},"totalFindings":{"type":"integer","minimum":0},"truncated":{"type":"boolean"},"rules":{"type":"array","items":{"type":"string"}}},"required":["linesAnalyzed","findings","totalFindings","truncated","rules"],"additionalProperties":false}},"required":["synthetic","source","sourceUrl","observedAt","license","limitations","data"],"additionalProperties":false}','builtin://code_scan',1000,0,'["security","code","analysis","tool"]',1,0,'/developers',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM providers WHERE id='provider_code_scan' AND user_id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO providers(id,user_id,name,description,reputation,created_at) SELECT 'provider_document_fingerprint',id,'Capora','Compute a SHA-256 digest and UTF-8 byte count of your supplied text. Optionally compare an expected digest to detect changes. Processes actual content. It does not verify issuer identity, authenticity, OCR or legal validity.',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM users WHERE id='user_demo' ON CONFLICT DO NOTHING;

INSERT INTO capabilities(id,provider_id,name,description,type,category,price_cents,pricing_unit,input_schema,output_schema,endpoint,expected_latency_ms,baseline_reliability,tags,async,synthetic,documentation_url,availability,created_at) SELECT 'document_fingerprint',id,'Document Fingerprint','Compute a SHA-256 digest and UTF-8 byte count of your supplied text. Optionally compare an expected digest to detect changes. Processes actual content. It does not verify issuer identity, authenticity, OCR or legal validity.','agent','Verification',10,'query','{"type":"object","properties":{"text":{"type":"string","minLength":1,"maxLength":100000,"default":"Document content to fingerprint."},"expectedSha256":{"type":"string","minLength":64,"maxLength":64}},"required":["text"],"additionalProperties":false}','{"type":"object","properties":{"synthetic":{"type":"boolean","enum":[false]},"source":{"type":"string"},"sourceUrl":{"type":"string"},"observedAt":{"type":"string"},"license":{"type":"string"},"limitations":{"type":"string"},"data":{"type":"object","properties":{"sha256":{"type":"string","minLength":64,"maxLength":64},"bytes":{"type":"integer","minimum":1},"matchesExpected":{"type":["boolean","null"]}},"required":["sha256","bytes","matchesExpected"],"additionalProperties":false}},"required":["synthetic","source","sourceUrl","observedAt","license","limitations","data"],"additionalProperties":false}','builtin://document_fingerprint',100,0,'["document","integrity","SHA-256","tool"]',0,0,'/developers',0,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM providers WHERE id='provider_document_fingerprint' AND user_id='user_demo' ON CONFLICT DO NOTHING;
